"""initial schema

Revision ID: 3a855653dff3
Revises: 
Create Date: 2026-09-21 06:43:19.850922
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '3a855653dff3'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # Required by the vector column and the trigram indexes below.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_collection_user_name')
    )
    op.create_table('profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('diet', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('allergies', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('dislikes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('likes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('pantry_staples', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('unit_system', sa.String(length=16), nullable=False),
    sa.Column('default_servings', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('profile_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('open', 'accepted', 'dismissed', name='suggestion_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'field', 'value', name='uq_suggestion_user_field_value')
    )
    op.create_index(op.f('ix_profile_suggestions_user_id'), 'profile_suggestions', ['user_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('instagram', 'short_video', 'web', 'photo', 'video_file', 'text', name='source_kind'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('page_text', sa.Text(), nullable=True),
    sa.Column('onscreen_text', sa.Text(), nullable=True),
    sa.Column('photo_text', sa.Text(), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_user_id'), 'sources', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('cuisine', 'course', 'diet', 'protein', 'time', 'technique', 'custom', name='tag_kind'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'video', 'audio', 'keyframe', 'thumbnail', name='media_kind'), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_source_id'), 'media', ['source_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_original', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('servings', sa.Float(), nullable=True),
    sa.Column('servings_unit', sa.String(length=64), nullable=True),
    sa.Column('prep_min', sa.Integer(), nullable=True),
    sa.Column('cook_min', sa.Integer(), nullable=True),
    sa.Column('total_min', sa.Integer(), nullable=True),
    sa.Column('hero_media_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'needs_review', 'ready', name='recipe_status'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('profile_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('equipment', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hero_media_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipes_search_tsv', 'recipes', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_recipes_title_trgm', 'recipes', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_recipes_user_status', 'recipes', ['user_id', 'status'], unique=False)
    op.create_index('ix_recipes_user_updated', 'recipes', ['user_id', 'updated_at'], unique=False)
    op.create_table('collection_items',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'recipe_id')
    )
    op.create_table('cook_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('cooked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('servings_made', sa.Float(), nullable=True),
    sa.CheckConstraint('rating is null or (rating >= 1 and rating <= 5)', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cook_log_recipe_id'), 'cook_log', ['recipe_id'], unique=False)
    op.create_table('ingest_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'fetching', 'transcribing', 'reading', 'extracting', 'done', 'needs_input', 'failed', name='job_status'), nullable=False),
    sa.Column('input_url', sa.Text(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('stage_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('needs_input_reason', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_jobs_status'), 'ingest_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_user_id'), 'ingest_jobs', ['user_id'], unique=False)
    op.create_table('ingredient_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_groups_recipe_id'), 'ingredient_groups', ['recipe_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('edit', 'rating', 'note', 'cooked', name='observation_kind'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_created_at'), 'observations', ['created_at'], unique=False)
    op.create_index(op.f('ix_observations_user_id'), 'observations', ['user_id'], unique=False)
    op.create_table('recipe_tags',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
    )
    op.create_table('steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timer_seconds', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_recipe_id'), 'steps', ['recipe_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('quantity_max', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_class', sa.Enum('volume', 'weight', 'count', 'length', 'none', name='unit_class'), nullable=False),
    sa.Column('item', sa.Text(), nullable=True),
    sa.Column('preparation', sa.Text(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('scalable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['ingredient_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_group_id'), 'ingredients', ['group_id'], unique=False)
    op.create_index('ix_ingredients_item_trgm', 'ingredients', ['item'], unique=False, postgresql_using='gin', postgresql_ops={'item': 'gin_trgm_ops'})
    # ### end Alembic commands ###


    op.execute(
        "CREATE INDEX ix_recipes_embedding_hnsw ON recipes "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_recipes_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredients_item_trgm', table_name='ingredients', postgresql_using='gin', postgresql_ops={'item': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_ingredients_group_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_steps_recipe_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_table('recipe_tags')
    op.drop_index(op.f('ix_observations_user_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_created_at'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_ingredient_groups_recipe_id'), table_name='ingredient_groups')
    op.drop_table('ingredient_groups')
    op.drop_index(op.f('ix_ingest_jobs_user_id'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_status'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_index(op.f('ix_cook_log_recipe_id'), table_name='cook_log')
    op.drop_table('cook_log')
    op.drop_table('collection_items')
    op.drop_index('ix_recipes_user_updated', table_name='recipes')
    op.drop_index('ix_recipes_user_status', table_name='recipes')
    op.drop_index('ix_recipes_title_trgm', table_name='recipes', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_recipes_search_tsv', table_name='recipes', postgresql_using='gin')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_media_source_id'), table_name='media')
    op.drop_table('media')
    op.drop_table('tags')
    op.drop_index(op.f('ix_sources_user_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_profile_suggestions_user_id'), table_name='profile_suggestions')
    op.drop_table('profile_suggestions')
    op.drop_table('profile')
    op.drop_table('collections')
    op.drop_table('users')
    # ### end Alembic commands ###
